/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppAttendanceRouteImport } from './routes/_app/attendance'
import { Route as AppClassesRouteImport } from './routes/_app/classes'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppEnrollmentsRouteImport } from './routes/_app/enrollments'
import { Route as AppPaymentsRouteImport } from './routes/_app/payments'
import { Route as AppScanRouteImport } from './routes/_app/scan'
import { Route as AppStudentEnrollmentRouteImport } from './routes/_app/student-enrollment'
import { Route as AppStudentsRouteImport } from './routes/_app/students'
import { Route as AppSubjectsRouteImport } from './routes/_app/subjects'
import { Route as AppTeachersRouteImport } from './routes/_app/teachers'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAttendanceRoute = AppAttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => AppRoute,
} as any)
const AppClassesRoute = AppClassesRouteImport.update({
  id: '/classes',
  path: '/classes',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppEnrollmentsRoute = AppEnrollmentsRouteImport.update({
  id: '/enrollments',
  path: '/enrollments',
  getParentRoute: () => AppRoute,
} as any)
const AppPaymentsRoute = AppPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => AppRoute,
} as any)
const AppScanRoute = AppScanRouteImport.update({
  id: '/scan',
  path: '/scan',
  getParentRoute: () => AppRoute,
} as any)
const AppStudentEnrollmentRoute = AppStudentEnrollmentRouteImport.update({
  id: '/student-enrollment',
  path: '/student-enrollment',
  getParentRoute: () => AppRoute,
} as any)
const AppStudentsRoute = AppStudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => AppRoute,
} as any)
const AppSubjectsRoute = AppSubjectsRouteImport.update({
  id: '/subjects',
  path: '/subjects',
  getParentRoute: () => AppRoute,
} as any)
const AppTeachersRoute = AppTeachersRouteImport.update({
  id: '/teachers',
  path: '/teachers',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/attendance': typeof AppAttendanceRoute
  '/classes': typeof AppClassesRoute
  '/dashboard': typeof AppDashboardRoute
  '/enrollments': typeof AppEnrollmentsRoute
  '/payments': typeof AppPaymentsRoute
  '/scan': typeof AppScanRoute
  '/student-enrollment': typeof AppStudentEnrollmentRoute
  '/students': typeof AppStudentsRoute
  '/subjects': typeof AppSubjectsRoute
  '/teachers': typeof AppTeachersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/attendance': typeof AppAttendanceRoute
  '/classes': typeof AppClassesRoute
  '/dashboard': typeof AppDashboardRoute
  '/enrollments': typeof AppEnrollmentsRoute
  '/payments': typeof AppPaymentsRoute
  '/scan': typeof AppScanRoute
  '/student-enrollment': typeof AppStudentEnrollmentRoute
  '/students': typeof AppStudentsRoute
  '/subjects': typeof AppSubjectsRoute
  '/teachers': typeof AppTeachersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/_app/attendance': typeof AppAttendanceRoute
  '/_app/classes': typeof AppClassesRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/enrollments': typeof AppEnrollmentsRoute
  '/_app/payments': typeof AppPaymentsRoute
  '/_app/scan': typeof AppScanRoute
  '/_app/student-enrollment': typeof AppStudentEnrollmentRoute
  '/_app/students': typeof AppStudentsRoute
  '/_app/subjects': typeof AppSubjectsRoute
  '/_app/teachers': typeof AppTeachersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/attendance'
    | '/classes'
    | '/dashboard'
    | '/enrollments'
    | '/payments'
    | '/scan'
    | '/student-enrollment'
    | '/students'
    | '/subjects'
    | '/teachers'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/attendance'
    | '/classes'
    | '/dashboard'
    | '/enrollments'
    | '/payments'
    | '/scan'
    | '/student-enrollment'
    | '/students'
    | '/subjects'
    | '/teachers'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_app/attendance'
    | '/_app/classes'
    | '/_app/dashboard'
    | '/_app/enrollments'
    | '/_app/payments'
    | '/_app/scan'
    | '/_app/student-enrollment'
    | '/_app/students'
    | '/_app/subjects'
    | '/_app/teachers'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/attendance': {
      id: '/_app/attendance'
      path: '/attendance'
      fullPath: '/attendance'
      preLoaderRoute: typeof AppAttendanceRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/classes': {
      id: '/_app/classes'
      path: '/classes'
      fullPath: '/classes'
      preLoaderRoute: typeof AppClassesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/enrollments': {
      id: '/_app/enrollments'
      path: '/enrollments'
      fullPath: '/enrollments'
      preLoaderRoute: typeof AppEnrollmentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/payments': {
      id: '/_app/payments'
      path: '/payments'
      fullPath: '/payments'
      preLoaderRoute: typeof AppPaymentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/scan': {
      id: '/_app/scan'
      path: '/scan'
      fullPath: '/scan'
      preLoaderRoute: typeof AppScanRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/student-enrollment': {
      id: '/_app/student-enrollment'
      path: '/student-enrollment'
      fullPath: '/student-enrollment'
      preLoaderRoute: typeof AppStudentEnrollmentRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/students': {
      id: '/_app/students'
      path: '/students'
      fullPath: '/students'
      preLoaderRoute: typeof AppStudentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/subjects': {
      id: '/_app/subjects'
      path: '/subjects'
      fullPath: '/subjects'
      preLoaderRoute: typeof AppSubjectsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/teachers': {
      id: '/_app/teachers'
      path: '/teachers'
      fullPath: '/teachers'
      preLoaderRoute: typeof AppTeachersRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAttendanceRoute: typeof AppAttendanceRoute
  AppClassesRoute: typeof AppClassesRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppEnrollmentsRoute: typeof AppEnrollmentsRoute
  AppPaymentsRoute: typeof AppPaymentsRoute
  AppScanRoute: typeof AppScanRoute
  AppStudentEnrollmentRoute: typeof AppStudentEnrollmentRoute
  AppStudentsRoute: typeof AppStudentsRoute
  AppSubjectsRoute: typeof AppSubjectsRoute
  AppTeachersRoute: typeof AppTeachersRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAttendanceRoute: AppAttendanceRoute,
  AppClassesRoute: AppClassesRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppEnrollmentsRoute: AppEnrollmentsRoute,
  AppPaymentsRoute: AppPaymentsRoute,
  AppScanRoute: AppScanRoute,
  AppStudentEnrollmentRoute: AppStudentEnrollmentRoute,
  AppStudentsRoute: AppStudentsRoute,
  AppSubjectsRoute: AppSubjectsRoute,
  AppTeachersRoute: AppTeachersRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
